apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ngl3txy6j-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:b0743938b7fcc87a59cebe8dbd6b7d2233cbec23@sha256:e93370608ebed7d3a3ab3421ab5baa4c6b30abe561d73b66e96b081e9b2b4150
          name: container-image
